#!/usr/bin/env php
<?php
declare(strict_types=1);

use Symfony\Component\Console\Application;
use Visualizer\RenderCommand;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add(new RenderCommand());
$application->run();
